theme: minima
title: Making a Site Without Any Knowledge
author: Leo He
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  These descriptions are not important at all.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  fragrantvagrant # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
